Content/Import Olympia Ledger Accounts/importOlympiaLedgerAccounts.json

This reverts commit 28448169bcf882a0713acfb0fffba90de754618f.

Revert "Update importOlympiaLedgerAccounts"

---

Content/0.8 - Create Account/createAccount.json

String added:
"createAccount_nameNewAccount_explanation": "This can be changed any time"

New string added for Create New Account

---

Content/0.4.3 - Authorized dApps/authorizedDapps.json

as per Zeplin https://zpl.io/Z0G9v81

persona data updated copies

---

Content/0.3 - Account/account.json

Forgot teh comma

---

Content/1.1 - Transaction Review/transactionReview.json

Fix the wrong string. Reverts the bad change done [here](https://github.com/radixdlt/apps-localization-src/commit/c3c2757489c0450e2f6d6a9b9b9c908e752b2e9a)

Fix select account title

---

Content/1.1.2 - Transaction Status/transactionStatus.json

Added string copies for tx messages error states.
More info here -> https://rdxworks.slack.com/archives/C03QFAWBRNX/p1695659078523719?thread_ts=1695571695.788379&cid=C03QFAWBRNX

ABW-2346 - String copies added for Tx messages.

---

Content/1.0 - Asset Transfer/assetTransfer.json

Link to Slack for reference -> https://rdxworks.slack.com/archives/C031A0V1A1W/p1699540837501269?thread_ts=1699518365.964829&cid=C031A0V1A1W

String copies added to max amount dialog.

---

Content/Error/error.json

Copy needed for this PR -> https://github.com/radixdlt/babylon-wallet-ios/pull/908

Copy added for tx failure

---

Content/Common/common.json

New strings required for updated Using dApps in TX Review

New using dApps strings

---

Content/0.4 - Wallet Settings/walletSettings.json
Content/0.4.5 - Preferences/preferences.json
Content/0.4.6 - Troubleshooting/troubleshooting.json

After having this merged in both platforms, we should make a separate PR deleting the following outdated files:
- [0.4 - Settings](https://github.com/radixdlt/apps-localization-src/blob/main/Content/0.4%20-%20Settings/settings.json)
- [0.4.5 - App Settings](https://github.com/radixdlt/apps-localization-src/blob/main/Content/0.4.5%20-%20App%20Settings/appSettings.json)
- [0.4.10 - Account Security & Settings](https://github.com/radixdlt/apps-localization-src/blob/main/Content/0.4.10%20-%20Account%20Security%20%26%20Settings/accountSecuritySettings.json)

New Settings strings

---

Content/0.4.1 - Linked Connectors/linkedConnectors.json
Content/0.4.14 - Configuration Backup/configurationBackup.json
Content/0.4.9 Account Recovery Scan/accountRecoveryScan.json
Content/Common/common.json

Restore correct state after need to merge https://github.com/radixdlt/apps-localization-src/pull/360

Undo unwanted changes from Crowdin

---

Content/0.4.1 - Linked Connectors/linkedConnectors.json
Content/0.4.14 - Configuration Backup/configurationBackup.json

Reverts radixdlt/apps-localization-src#370

Revert "Tabs not spaces"

---

Content/1.1.1 - Customize Network Fees/customizeNetworkFees.json

Based on [ticket](https://radixdlt.atlassian.net/browse/ABW-3220)

Change message for insufficient balance

---

Content/Onboarding/onboarding.json
Content/Security Problems/securityProblems.json

Adds a new root key, `securityProblems`, with third level keys like `accountCard` and `configurationBackup`.
A follow up PR will remove existing problem strings from `securityCenter` and `configurationBackup`.

All Security Center related strings

---

Content/0.9 - Dapp Request/dappRequest.json

JIRA ticket: [ABW-3385](https://radixdlt.atlassian.net/browse/ABW-3385)
[ABW-3385]: https://radixdlt.atlassian.net/browse/ABW-3385?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ABW-3385] `dAppRequest_chooseAccountsOneTime_subtitleExactly` fix

---

Content/0.3.1 - Asset Details/assetDetails.json

The string displaying how many minutes are remaining to claim the XRD has changed https://zpl.io/Gn71PYY

Add new strings for ready to claim

---

Content/0.2.1 - HomePage Carousel/homePageCarousel.json
Content/0.4.1 - Linked Connectors/linkedConnectors.json
Content/Scan QR/scanQR.json

Changes for new Zeplin designs: [Link Connector](https://zpl.io/noMqM9A) & [Carousel](https://app.zeplin.io/project/639c7e7ab391bb15ac5d25fa/screen/667db449808b0db392a47fd7).

Link Connector + Carousel updated Strings

---

Content/0.3.2 - Account Settings/accountSettings.json
Content/0.9 - Dapp Request/dappRequest.json

- [Account Settings](https://zpl.io/Am8AgkO)
- [Persona Login 1](https://zpl.io/jZXwBWA) & [Persona Login 2](https://zpl.io/kDlndog)

Account Settings & Persona Login updates

---

Content/0.2 - HomePage/homePage.json

Adds a new String to see if the Crowdin bot decides to detect changes correctly.
Should be removed after.

Add placeholder String

---

Content/1.0 - Asset Transfer/assetTransfer.json

[Ticket](https://radixdlt.atlassian.net/browse/ABW-2774)

Deposit status Strings

---

Content/0.4.8 - Seed Phrases/seedPhrases.json
Content/1.1 - Transaction Review/transactionReview.json

Removing strings obsoleted by [#442](https://github.com/radixdlt/apps-localization-src/pull/442) and [#443](https://github.com/radixdlt/apps-localization-src/pull/443)

Removing obsolete strings

---

Content/0.2 - HomePage/homePage.json
Content/0.4.3 - Authorized dApps/authorizedDapps.json

- Adds Strings for [Approved Dapps view](https://zpl.io/o01ezrE) & [Home Account rows](https://zpl.io/gg8d08N)

Account Locker Claim strings

---

Content/Scan QR/scanQR.json

Needed for https://app.zeplin.io/project/639c7e7ab391bb15ac5d25fa/screen/6478ced3c9eced1c383481f2

RadixConnect Learn more string

---

Content/0.4.1 - Linked Connectors/linkedConnectors.json

Based on updated [designs](https://zpl.io/p01El4l)

Update LinkedConnectors subtitle

---

Content/0.4.1 - Linked Connectors/linkedConnectors.json

[Designs](https://zpl.io/Bw1LBEA)

Rename Connector Strings

---

Content/0.4.6 - Profile Backup/profileBackup.json
Content/Recover Profile Backup/recoverProfileBackup.json

Need confirmation from someone of Android team that these Strings aren't used on their side.

Remove unused Strings

---

Content/0.9 - Dapp Request/dappRequest.json

[Verify Persona](https://zpl.io/gg8d9eD) & [Verify Accounts](https://zpl.io/ezwly1Y)

Add Strings for Proof of Ownership views

---

Content/FactorSources/factorSources.json

Factor Source card component strings -> [ABW-3958](https://radixdlt.atlassian.net/browse/ABW-3958)
[ABW-3958]: https://radixdlt.atlassian.net/browse/ABW-3958?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ABW-3958] Factor Source card strings

---

Content/InfoLink/infoLink.json
Content/Shield Setup Prepare Factors/shieldSetupPrepareFactors.json

[Reference designs](https://zpl.io/9Nqg7Xy)

Shield Prepare Factors strings

---

Content/0.4.13 - Security Factors/securityFactors.json
Content/Security Problems/securityProblems.json

[Designs](https://zpl.io/XKYDON8)

Security Factors new Strings

---

Content/FactorSources/factorSources.json

Two missing Strings from https://github.com/radixdlt/apps-localization-src/pull/544

missing Strings from #544

---

Content/FactorSources/factorSources.json
Content/RenameLabel/renameLabel.json

- Strings for the detail view of each Factor Source ([ref](https://zpl.io/jpZEGOx))
- Strings for renaming a `FactorSource`/`Connector`/`Account`

Factor Source detail + Rename label

---

Content/0.4.13 - Security Factors/securityFactors.json

for this [flow](https://zpl.io/Zq0Yl8w)

Add copies for select factor source flow

---

Content/FactorSources/factorSources.json

Support for this [design](https://zpl.io/dRRxxmp)

Factor Source detail updates

---

Content/0.4.13 - Security Factors/securityFactors.json

for Select Factor Type [view](https://zpl.io/wyqB6Bd)

Missing String

---

Content/2.0.1 - Security Shield Preparation/shieldSetupStatus.json
Content/FactorSources/factorSources.json

[Designs](https://zpl.io/8EEE8pw)

Strings for change main factor source

---

Content/1.1.5 - Recovery Transaction States/recoveryTransactionStates.json

Pre-auth sign [fail](https://app.zeplin.io/project/639c7e7ab391bb15ac5d25fa/screen/67927a57171656437cc150ab)

Add pre-auth strings

---

Content/Authorization/authorization.json

Add authorization strings

---

Content/FactorSources/factorSources.json

[Ref](https://rdxworks.slack.com/archives/C031A0V1A1W/p1738794756333439?thread_ts=1738768493.843369&cid=C031A0V1A1W)

Spot check Strings

---

Content/Arculus/addArculus.json

To be displayed when user scans a valid card in Add Arculus flow.

Add arculus seed phrase instructions
